--[[
    ╔═══════════════════════════════════════════════╗
    ║           AUTO ANSWER - WORD LIST             ║
    ║       Made By CozzyBruh                       ║
    ╚═══════════════════════════════════════════════╝
    
    Add more words here to improve coverage.
    All words should be UPPERCASE.
    The more words you add, the better the auto answer works.
]]

local WordList = {
    -- A
    "ABANDON","ABACUS","ABILITY","ABLE","ABOUT","ABOVE","ABROAD","ABSENCE","ABSOLUTE","ABSORB",
    "ABSTRACT","ABSURD","ABUSE","ACADEMY","ACCELERATE","ACCENT","ACCEPT","ACCESS","ACCIDENT",
    "ACCOUNT","ACCURATE","ACHIEVE","ACID","ACKNOWLEDGE","ACORN","ACQUIRE","ACROSS","ACTION",
    "ACTIVATE","ACTIVE","ACTIVITY","ACTOR","ACTUAL","ADAPT","ADDRESS","ADEQUATE","ADJUST",
    "ADMIRAL","ADMIT","ADOPT","ADULT","ADVANCE","ADVANTAGE","ADVENTURE","ADVICE","AFFAIR",
    "AFFECT","AFFORD","AFRAID","AFTER","AFTERNOON","AGAIN","AGAINST","AGENT","AGREE","AHEAD",
    "AIRCRAFT","AIRPLANE","ALARM","ALBUM","ALCOHOL","ALERT","ALIEN","ALIGN","ALIVE","ALLEY",
    "ALLOW","ALMOST","ALONE","ALPHA","ALREADY","ALTER","ALWAYS","AMATEUR","AMAZING","AMBITION",
    "AMBULANCE","AMONG","AMOUNT","AMUSE","ANCHOR","ANCIENT","ANGEL","ANGER","ANGLE","ANGRY",
    "ANIMAL","ANKLE","ANNOUNCE","ANNUAL","ANOTHER","ANSWER","ANTENNA","ANTIQUE","ANXIETY",
    "APART","APOLOGY","APPEAR","APPLE","APPLY","APPROACH","APPROVE","APRIL","ARCH","ARCTIC",
    "ARENA","ARGUE","ARMOR","ARMY","AROUND","ARRANGE","ARREST","ARRIVE","ARROW","ARTICLE",
    "ARTIST","ARTWORK","ASPECT","ASSAULT","ASSET","ASSIST","ASSUME","ASTHMA","ATHLETE","ATOM",
    "ATTACK","ATTEMPT","ATTEND","ATTITUDE","ATTRACT","AUCTION","AUGUST","AUNT","AUTHOR","AUTO",
    "AUTUMN","AVERAGE","AVOCADO","AVOID","AWAKE","AWARE","AWFUL","AWKWARD",

    -- B
    "BABY","BACHELOR","BACON","BADGE","BALANCE","BALCONY","BALL","BAMBOO","BANANA","BAND",
    "BANK","BARREL","BASE","BASIC","BASKET","BATTLE","BEACH","BEAN","BEAUTY","BECAUSE","BECOME",
    "BEEF","BEFORE","BEGIN","BEHAVE","BEHIND","BELIEVE","BELL","BELOW","BELT","BENCH","BENEFIT",
    "BEST","BETRAY","BETTER","BETWEEN","BEYOND","BICYCLE","BILLION","BIRD","BIRTH","BITTER",
    "BLACK","BLADE","BLAME","BLANKET","BLAST","BLEAK","BLESS","BLIND","BLOOD","BLOSSOM","BLOW",
    "BLUE","BLUR","BLUSH","BOARD","BOAT","BODY","BOIL","BOMB","BONE","BONUS","BOOK","BOOST",
    "BORDER","BORING","BORN","BOSS","BOTTOM","BOUNCE","BRACKET","BRAIN","BRAND","BRASS","BRAVE",
    "BREAD","BREEZE","BRICK","BRIDGE","BRIEF","BRIGHT","BRING","BROAD","BROCCOLI","BROKEN",
    "BRONZE","BROOM","BROTHER","BROWN","BRUSH","BUBBLE","BUCKET","BUDGET","BUFFALO","BUILD",
    "BULK","BULLET","BUNDLE","BURDEN","BURGER","BURST","BUSINESS","BUSY","BUTTER","BUYER",

    -- C
    "CABIN","CABLE","CACTUS","CAGE","CAKE","CALL","CALM","CAMERA","CAMP","CAMPAIGN","CANAL",
    "CANCEL","CANDY","CANNON","CAPABLE","CAPITAL","CAPTAIN","CARBON","CARD","CARGO","CARPET",
    "CARRY","CART","CASE","CASH","CASINO","CASTLE","CASUAL","CATALOG","CATCH","CATEGORY",
    "CATTLE","CAUGHT","CAUSE","CAUTION","CAVE","CEILING","CELERY","CEMENT","CENSUS","CENTURY",
    "CEREAL","CERTAIN","CHAIR","CHALK","CHAMPION","CHANCE","CHANGE","CHANNEL","CHAPTER",
    "CHARGE","CHARM","CHART","CHASE","CHEAP","CHECK","CHEESE","CHEF","CHERRY","CHEST",
    "CHICKEN","CHIEF","CHILD","CHIMNEY","CHOICE","CHOOSE","CHUNK","CHURCH","CIGAR","CINEMA",
    "CIRCLE","CITIZEN","CITY","CIVIL","CLAIM","CLAP","CLARIFY","CLASS","CLASSIC","CLEAN",
    "CLEAR","CLEVER","CLICK","CLIENT","CLIFF","CLIMB","CLINIC","CLIP","CLOCK","CLOSE","CLOTH",
    "CLOUD","CLOWN","CLUB","CLUE","CLUSTER","CLUTCH","COACH","COAST","COCONUT","CODE","COFFEE",
    "COIL","COIN","COLLECT","COLOR","COLUMN","COMBINE","COME","COMFORT","COMIC","COMMON",
    "COMPANY","CONCERT","CONDUCT","CONFIRM","CONGRESS","CONNECT","CONSIDER","CONTROL",
    "CONVINCE","COOK","COOL","COPPER","COPY","CORAL","CORE","CORN","CORRECT","COST","COTTON",
    "COUCH","COUNTRY","COUPLE","COURSE","COUSIN","COVER","COYOTE","CRACK","CRADLE","CRAFT",
    "CRASH","CRATER","CRAWL","CRAZY","CREAM","CREDIT","CREEK","CREW","CRICKET","CRIME",
    "CRISIS","CRITIC","CROP","CROSS","CROUCH","CROWD","CRUCIAL","CRUEL","CRUISE","CRUMBLE",
    "CRUSH","CRYSTAL","CUBE","CULTURE","CURIOUS","CURRENT","CURTAIN","CURVE","CUSHION",
    "CUSTOM","CYCLE",

    -- D
    "DAMAGE","DAMP","DANCE","DANGER","DARING","DASH","DAUGHTER","DAWN","DEAL","DEBATE",
    "DEBRIS","DECADE","DECEMBER","DECIDE","DECLINE","DECORATE","DECREASE","DEER","DEFENSE",
    "DEFINE","DEGREE","DELAY","DELIVER","DEMAND","DEMISE","DENIAL","DENTIST","DENY","DEPART",
    "DEPEND","DEPOSIT","DEPTH","DEPUTY","DERIVE","DESCRIBE","DESERT","DESIGN","DESK","DESPAIR",
    "DESTROY","DETAIL","DETECT","DEVELOP","DEVICE","DEVOTE","DIAGRAM","DIAL","DIAMOND","DIARY",
    "DICE","DIESEL","DIET","DIFFER","DIGITAL","DIGNITY","DILEMMA","DINNER","DINOSAUR","DIRECT",
    "DIRT","DISAGREE","DISCOVER","DISEASE","DISH","DISMISS","DISORDER","DISPLAY","DISTANCE",
    "DIVERT","DIVIDE","DIVORCE","DIZZY","DOCTOR","DOCUMENT","DOLL","DOLPHIN","DOMAIN","DONATE",
    "DONKEY","DONOR","DOOR","DOSE","DOUBLE","DOVE","DRAFT","DRAGON","DRAMA","DRASTIC","DRAW",
    "DREAM","DRESS","DRIFT","DRILL","DRINK","DRIP","DRIVE","DROP","DRUM","DUCK","DUMB","DUNE",
    "DURING","DUST","DUTCH","DUTY","DWARF","DYNAMIC",

    -- E
    "EAGER","EAGLE","EARLY","EARN","EARTH","EASILY","EAST","EASY","ECHO","ECOLOGY","ECONOMY",
    "EDGE","EDIT","EDUCATE","EFFORT","EIGHT","EITHER","ELBOW","ELDER","ELECTRIC","ELEGANT",
    "ELEMENT","ELEPHANT","ELEVATOR","ELITE","ELSE","EMBARK","EMBODY","EMBRACE","EMERGE",
    "EMOTION","EMPLOY","EMPOWER","EMPTY","ENABLE","ENACT","ENCOUNTER","ENCOURAGE","ENDLESS",
    "ENDORSE","ENEMY","ENERGY","ENFORCE","ENGAGE","ENGINE","ENHANCE","ENJOY","ENLIST","ENOUGH",
    "ENRICH","ENROLL","ENSURE","ENTER","ENTIRE","ENTRY","ENVELOPE","EPISODE","EQUAL","EQUIP",
    "ERODE","EROSION","ERROR","ERUPT","ESCAPE","ESSAY","ESSENCE","ESTATE","ETERNAL","ETHICS",
    "EVIDENCE","EVIL","EVOLVE","EXACT","EXAMPLE","EXCESS","EXCHANGE","EXCITE","EXCLUDE",
    "EXCUSE","EXECUTE","EXERCISE","EXHAUST","EXHIBIT","EXILE","EXIST","EXIT","EXOTIC","EXPAND",
    "EXPECT","EXPIRE","EXPLAIN","EXPOSE","EXPRESS","EXTEND","EXTRA","EYEBROW",

    -- F
    "FABRIC","FACE","FACULTY","FADE","FAINT","FAITH","FALL","FALSE","FAME","FAMILY","FAMOUS",
    "FANCY","FANTASY","FARM","FASHION","FATAL","FATHER","FATIGUE","FAULT","FAVORITE","FEATURE",
    "FEBRUARY","FEDERAL","FEED","FEEL","FEMALE","FENCE","FESTIVAL","FETCH","FEVER","FIBER",
    "FICTION","FIELD","FIGURE","FILE","FILL","FILM","FILTER","FINAL","FIND","FINE","FINGER",
    "FINISH","FIRE","FIRM","FIRST","FISCAL","FISH","FITNESS","FLAG","FLAME","FLASH","FLAT",
    "FLAVOR","FLEE","FLIGHT","FLIP","FLOAT","FLOCK","FLOOR","FLOWER","FLUID","FLUSH","FOAM",
    "FOCUS","FOIL","FOLD","FOLLOW","FOOD","FOOT","FORCE","FOREST","FORGET","FORK","FORTUNE",
    "FORUM","FORWARD","FOSSIL","FOSTER","FOUND","FRAGILE","FRAME","FREQUENT","FRESH","FRIEND",
    "FRINGE","FROG","FRONT","FROST","FROZEN","FRUIT","FUEL","FUNNY","FURNACE","FURY","FUTURE",

    -- G
    "GADGET","GAIN","GALAXY","GALLERY","GAME","GARAGE","GARBAGE","GARDEN","GARLIC","GARMENT",
    "GASP","GATE","GATHER","GAUGE","GAZE","GENERAL","GENIUS","GENRE","GENTLE","GENUINE",
    "GESTURE","GHOST","GIANT","GIFT","GIGGLE","GINGER","GIRAFFE","GIVE","GLAD","GLANCE",
    "GLARE","GLASS","GLEAM","GLOBE","GLOOM","GLORY","GLOVE","GLOW","GLUE","GOAT","GODDESS",
    "GOLD","GOOD","GOOSE","GORILLA","GOSPEL","GOSSIP","GOVERN","GOWN","GRAB","GRACE","GRAIN",
    "GRAND","GRANT","GRAPE","GRASS","GRAVITY","GREAT","GREEN","GRID","GRIEF","GRIT","GROCERY",
    "GROUP","GROW","GRUNT","GUARD","GUESS","GUIDE","GUILT","GUITAR",

    -- H
    "HABIT","HAIR","HALF","HAMMER","HAMSTER","HAND","HAPPY","HARBOR","HARD","HARSH","HARVEST",
    "HAVE","HAWK","HAZARD","HEAD","HEALTH","HEART","HEAVY","HEDGEHOG","HEIGHT","HELLO","HELMET",
    "HELP","HERO","HIRE","HISTORY","HOBBY","HOCKEY","HOLD","HOLE","HOLIDAY","HOLLOW","HOME",
    "HONEY","HOOD","HOPE","HORN","HORROR","HORSE","HOSPITAL","HOST","HOTEL","HOUR","HOVER",
    "HUGE","HUMAN","HUMBLE","HUMOR","HUNDRED","HUNGRY","HUNT","HURDLE","HURRY","HURT",
    "HUSBAND","HYBRID",

    -- I
    "ICON","IDEA","IDENTIFY","IDLE","IGNORE","ILLEGAL","ILLNESS","IMAGE","IMITATE","IMMENSE",
    "IMMUNE","IMPACT","IMPOSE","IMPROVE","IMPULSE","INCH","INCLUDE","INCOME","INCREASE","INDEX",
    "INDICATE","INDOOR","INDUSTRY","INFANT","INFLICT","INFORM","INITIAL","INJECT","INMATE",
    "INNER","INNOCENT","INPUT","INQUIRY","INSANE","INSECT","INSIDE","INSPIRE","INSTALL",
    "INTACT","INTEREST","INTO","INVEST","INVITE","INVOLVE","IRON","ISLAND","ISOLATE","ISSUE",
    "ITEM","IVORY",

    -- J
    "JACKET","JAGUAR","JAZZ","JEALOUS","JEANS","JELLY","JEWEL","JOIN","JOKE","JOURNEY","JUDGE",
    "JUICE","JUMP","JUNGLE","JUNIOR","JUNK","JUST",

    -- K
    "KANGAROO","KEEN","KEEP","KETCHUP","KICK","KIDNEY","KIND","KINGDOM","KISS","KITCHEN","KITE",
    "KITTEN","KIWI","KNEE","KNIFE","KNOCK","KNOW",

    -- L
    "LABEL","LABOR","LADDER","LADY","LAKE","LAMP","LANGUAGE","LAPTOP","LARGE","LATER","LATIN",
    "LAUGH","LAUNDRY","LAVA","LAWN","LAWSUIT","LAYER","LAZY","LEADER","LEAF","LEARN","LEAVE",
    "LECTURE","LEFT","LEGAL","LEGEND","LEISURE","LEMON","LEND","LENGTH","LENS","LEOPARD",
    "LESSON","LETTER","LEVEL","LIBERTY","LIBRARY","LICENSE","LIFE","LIFT","LIGHT","LIKE","LIMB",
    "LIMIT","LINK","LION","LIQUID","LIST","LITTLE","LIVE","LIZARD","LOAD","LOAN","LOBSTER",
    "LOCAL","LOCK","LOGIC","LONELY","LONG","LOOP","LOTTERY","LOUD","LOUNGE","LOVE","LOYAL",
    "LUCKY","LUGGAGE","LUMBER","LUNAR","LUNCH","LUXURY",

    -- M
    "MACHINE","MAGIC","MAGNET","MAID","MAIN","MAJOR","MAKE","MAMMAL","MANAGE","MANDATE",
    "MANGO","MANSION","MANUAL","MAPLE","MARBLE","MARCH","MARGIN","MARINE","MARKET","MARRIAGE",
    "MASK","MASS","MASTER","MATCH","MATERIAL","MATH","MATRIX","MATTER","MAXIMUM","MAZE",
    "MEADOW","MEAN","MEASURE","MEAT","MECHANIC","MEDIA","MELODY","MELT","MEMBER","MEMORY",
    "MENTION","MENTOR","MERCY","MERGE","MERIT","MERRY","MESH","MESSAGE","METAL","METHOD",
    "MIDDLE","MIDNIGHT","MILK","MILLION","MIMIC","MIND","MINIMUM","MINOR","MINUTE","MIRACLE",
    "MIRROR","MISERY","MISS","MISTAKE","MIXTURE","MOBILE","MODEL","MODIFY","MOMENT","MONITOR",
    "MONKEY","MONSTER","MONTH","MOON","MORAL","MORE","MORNING","MOSQUITO","MOTHER","MOTION",
    "MOTOR","MOUNTAIN","MOUSE","MOVE","MOVIE","MUCH","MUFFIN","MULE","MULTIPLY","MUSCLE",
    "MUSEUM","MUSHROOM","MUSIC","MUST","MUTUAL","MYSELF","MYSTERY","MYTH",

    -- N
    "NAIVE","NAME","NAPKIN","NARROW","NASTY","NATION","NATURE","NEAR","NECK","NEED","NEGATIVE",
    "NEGLECT","NEITHER","NEPHEW","NERVE","NEST","NETWORK","NEUTRAL","NEVER","NEWS","NEXT",
    "NICE","NIGHT","NOBLE","NOISE","NOMINEE","NORMAL","NORTH","NOSE","NOTABLE","NOTHING",
    "NOTICE","NOVEL","NUCLEAR","NUMBER","NURSE",

    -- O
    "OBTAIN","OBVIOUS","OCCUR","OCEAN","OCTOBER","ODDS","OFFER","OFFICE","OFTEN","OLIVE",
    "OLYMPIC","OMIT","ONCE","ONION","ONLINE","ONLY","OPEN","OPERA","OPINION","OPPOSE","OPTION",
    "ORANGE","ORBIT","ORCHARD","ORDER","ORDINARY","ORGAN","ORIENT","ORIGINAL","ORPHAN",
    "OSTRICH","OTHER","OUTDOOR","OUTER","OUTPUT","OUTSIDE","OVAL","OVEN","OVER","OWN","OWNER",
    "OXYGEN","OYSTER","OZONE",

    -- P
    "PACT","PADDLE","PAGE","PAIR","PALACE","PALM","PANDA","PANEL","PANIC","PANTHER","PAPER",
    "PARADE","PARENT","PARK","PARROT","PARTY","PASS","PATCH","PATH","PATIENT","PATROL",
    "PATTERN","PAUSE","PAVE","PAYMENT","PEACE","PEANUT","PEAR","PEASANT","PELICAN","PENALTY",
    "PENCIL","PEOPLE","PEPPER","PERFECT","PERMIT","PERSON","PHONE","PHOTO","PHRASE","PHYSICAL",
    "PIANO","PICNIC","PICTURE","PIECE","PILOT","PINK","PIONEER","PIPE","PISTOL","PITCH",
    "PIZZA","PLACE","PLANET","PLASTIC","PLATE","PLAY","PLEASE","PLEDGE","PLUCK","PLUG",
    "PLUNGE","POCKET","POEM","POET","POINT","POLAR","POLE","POLICE","POND","PONY","POOL",
    "POPULAR","PORK","PORTION","POSITION","POSSIBLE","POST","POTATO","POTTERY","POVERTY",
    "POWDER","POWER","PRACTICE","PRAISE","PREDICT","PREFER","PREPARE","PRESENT","PRETTY",
    "PREVENT","PRICE","PRIDE","PRIMARY","PRINT","PRIORITY","PRISON","PRIVATE","PRIZE",
    "PROBLEM","PROCESS","PRODUCE","PROFIT","PROGRAM","PROJECT","PROMOTE","PROOF","PROPERTY",
    "PROSPER","PROTECT","PROUD","PROVIDE","PUBLIC","PUDDING","PULL","PULP","PULSE","PUMPKIN",
    "PUNCH","PUPIL","PUPPY","PURCHASE","PURITY","PURPOSE","PURSE","PUSH","PUZZLE","PYRAMID",

    -- Q
    "QUALITY","QUANTUM","QUARTER","QUESTION","QUICK","QUIET","QUIT","QUIZ","QUOTE",

    -- R
    "RABBIT","RACCOON","RACE","RACK","RADAR","RADIO","RAIL","RAIN","RAISE","RALLY","RAMP",
    "RANCH","RANDOM","RANGE","RAPID","RARE","RATE","RATHER","RAVEN","RAZOR","READY","REAL",
    "REASON","REBEL","REBUILD","RECALL","RECEIVE","RECIPE","RECORD","RECYCLE","REDUCE",
    "REFLECT","REFORM","REGION","REGRET","REGULAR","REJECT","RELAX","RELEASE","RELIEF","RELY",
    "REMAIN","REMEMBER","REMIND","REMOVE","RENDER","RENEW","RENT","REOPEN","REPAIR","REPEAT",
    "REPLACE","REPORT","REQUIRE","RESCUE","RESEMBLE","RESIST","RESOURCE","RESPONSE","RESULT",
    "RETIRE","RETREAT","RETURN","REUNION","REVEAL","REVIEW","REWARD","RHYTHM","RIBBON","RICE",
    "RICH","RIDE","RIDGE","RIFLE","RIGHT","RIGID","RING","RIOT","RIPPLE","RISK","RITUAL",
    "RIVAL","RIVER","ROAD","ROAST","ROBOT","ROBUST","ROCKET","ROMANCE","ROOF","ROOKIE","ROOM",
    "ROSE","ROTATE","ROUGH","ROUND","ROUTE","ROYAL","RUBBER","RUDE","RUGBY","RULER","RURAL",

    -- S
    "SADDLE","SADNESS","SAFE","SAIL","SALAD","SALMON","SALON","SALT","SALUTE","SAME","SAMPLE",
    "SAND","SATISFY","SAUCE","SAUSAGE","SAVE","SCALE","SCAN","SCARE","SCATTER","SCENE",
    "SCHEME","SCHOOL","SCIENCE","SCISSORS","SCORPION","SCOUT","SCRAP","SCREEN","SCRIPT",
    "SCRUB","SEARCH","SEASON","SEAT","SECOND","SECRET","SECTION","SECURITY","SEED","SEEK",
    "SEGMENT","SELECT","SELL","SEMINAR","SENIOR","SENSE","SENTENCE","SERIES","SERVICE",
    "SESSION","SETTLE","SETUP","SEVEN","SHADOW","SHAFT","SHALLOW","SHARE","SHARK","SHARP",
    "SHED","SHELL","SHERIFF","SHIELD","SHIFT","SHINE","SHIP","SHIVER","SHOCK","SHOE","SHOOT",
    "SHOP","SHORT","SHOULDER","SHOVE","SHRIMP","SHUFFLE","SHUT","SIBLING","SICK","SIDE",
    "SIEGE","SIGHT","SIGN","SILENT","SILK","SILLY","SILVER","SIMILAR","SIMPLE","SINCE",
    "SISTER","SITUATE","SIZE","SKATE","SKETCH","SKILL","SKIN","SKIRT","SKULL","SLAB","SLAM",
    "SLEEP","SLENDER","SLICE","SLIDE","SLIGHT","SLIM","SLOGAN","SLOT","SLOW","SLUSH","SMALL",
    "SMART","SMILE","SMOKE","SMOOTH","SNACK","SNAKE","SNAP","SNIFF","SNOW","SOAP","SOCCER",
    "SOCIAL","SOCK","SODA","SOFT","SOLAR","SOLDIER","SOLID","SOLUTION","SOLVE","SOMEONE",
    "SONG","SOON","SORRY","SORT","SOUL","SOUND","SOUP","SOURCE","SOUTH","SPACE","SPARE",
    "SPATIAL","SPAWN","SPEAK","SPECIAL","SPEED","SPELL","SPEND","SPHERE","SPICE","SPIDER",
    "SPIKE","SPIN","SPIRIT","SPLIT","SPONSOR","SPOON","SPORT","SPOT","SPRAY","SPREAD",
    "SPRING","SPY","SQUARE","SQUEEZE","SQUIRREL","STABLE","STADIUM","STAFF","STAGE","STAIRS",
    "STAMP","STAND","START","STATE","STAY","STEAK","STEEL","STEM","STEP","STEREO","STICK",
    "STILL","STING","STOCK","STOMACH","STONE","STOOL","STORY","STOVE","STRATEGY","STREET",
    "STRIKE","STRONG","STRUGGLE","STUDENT","STUFF","STUMBLE","STYLE","SUBJECT","SUBMIT",
    "SUBWAY","SUCCESS","SUCH","SUDDEN","SUFFER","SUGAR","SUGGEST","SUIT","SUMMER","SUNNY",
    "SUNSET","SUPER","SUPPLY","SUPREME","SURE","SURFACE","SURGE","SURPRISE","SURROUND",
    "SURVEY","SUSPECT","SUSTAIN","SWALLOW","SWAMP","SWAP","SWARM","SWEET","SWIM","SWING",
    "SWITCH","SWORD","SYMBOL","SYMPTOM","SYRUP","SYSTEM",

    -- T
    "TABLE","TACKLE","TALENT","TALK","TANK","TAPE","TARGET","TASK","TASTE","TATTOO","TAXI",
    "TEACH","TEAM","TELL","TENANT","TEND","TERM","TEST","TEXT","THANK","THAT","THEME","THEN",
    "THEORY","THERE","THEY","THING","THIS","THOUGHT","THREE","THRIVE","THROW","THUMB",
    "THUNDER","TICKET","TIDE","TIGER","TILT","TIMBER","TIME","TINY","TIRED","TISSUE","TITLE",
    "TOAST","TOBACCO","TODAY","TODDLER","TOGETHER","TOILET","TOKEN","TOMATO","TOMORROW","TONE",
    "TONGUE","TONIGHT","TOOL","TOOTH","TOPIC","TOPPLE","TORCH","TORNADO","TORTOISE","TOSS",
    "TOTAL","TOURIST","TOWARD","TOWER","TOWN","TRACK","TRADE","TRAFFIC","TRAGIC","TRAIN",
    "TRANSFER","TRAP","TRASH","TRAVEL","TRAY","TREAT","TREE","TREND","TRIAL","TRIBE","TRICK",
    "TRIGGER","TRIM","TRIP","TROPHY","TROUBLE","TRUCK","TRUE","TRULY","TRUMPET","TRUST",
    "TRUTH","TUBE","TUNA","TUNNEL","TURKEY","TURN","TURTLE","TWELVE","TWENTY","TWICE","TWIN",
    "TWIST","TYPE","TYPICAL",

    -- U
    "UGLY","UMBRELLA","UNABLE","UNAWARE","UNCLE","UNCOVER","UNDER","UNDO","UNFAIR","UNFOLD",
    "UNHAPPY","UNIFORM","UNION","UNIQUE","UNIT","UNIVERSE","UNKNOWN","UNLOCK","UNTIL",
    "UNUSUAL","UNVEIL","UPDATE","UPGRADE","UPHOLD","UPON","UPPER","UPSET","URBAN","USAGE",
    "USEFUL","USELESS","USUAL","UTILITY",

    -- V
    "VACANT","VACUUM","VAGUE","VALID","VALLEY","VALVE","VANISH","VAPOR","VARIOUS","VAST",
    "VAULT","VEHICLE","VELVET","VENDOR","VENTURE","VENUE","VERB","VERIFY","VERSION","VERY",
    "VESSEL","VETERAN","VIABLE","VIBRANT","VICIOUS","VICTORY","VIDEO","VIEW","VILLAGE",
    "VINTAGE","VIOLIN","VIRTUAL","VIRUS","VISA","VISIT","VISUAL","VITAL","VIVID","VOCAL",
    "VOICE","VOID","VOLCANO","VOLUME","VOTE","VOYAGE",

    -- W
    "WAGE","WAGON","WAIT","WALK","WALL","WALNUT","WANT","WARFARE","WARM","WARRIOR","WASH",
    "WASP","WASTE","WATER","WAVE","WAY","WEALTH","WEAPON","WEAR","WEASEL","WEATHER","WEB",
    "WEDDING","WEEKEND","WEIRD","WELCOME","WEST","WHALE","WHEAT","WHEEL","WHEN","WHERE","WHIP",
    "WHISPER","WIDE","WIDTH","WIFE","WILD","WILL","WIN","WINDOW","WINE","WING","WINNER",
    "WINTER","WIRE","WISDOM","WISE","WISH","WITNESS","WOLF","WOMAN","WONDER","WOOD","WOOL",
    "WORD","WORK","WORLD","WORRY","WORTH","WRAP","WRECK","WRESTLE","WRIST","WRITE","WRONG",

    -- X Y Z
    "XEROX","YACHT","YARD","YEAR","YELLOW","YOUNG","YOUTH","ZEBRA","ZERO","ZONE","ZOO"
}

return WordList
